### PR TITLE
MachineITSvcs: Updating readme.txt

### PR DESCRIPTION
**Pull request by MachineITSvcs**
Provided additional information in readme.txt

### CODE REVIEW

**Comment by MachineITSvcs** [comment]
Great update earlier, by the way! I forgot the websites feature didn't work (haven't tried to use it in quite a while). Also, I'm curious how much work it would entail to create a form builder (of sorts), or function builder in the WordPress Dashboard that would be saved and loaded from the database (to prevent loss of custom files on plugin update). Just a thought.

**Review by ole1986 — APPROVED** [review]

**Comment by ole1986** [comment]
I think the ultimate goal would be to have gutenberg blocks shipped with wordpress 5.X

**Comment by MachineITSvcs** [comment]
That would be great as well. Also, is the Website/Database filter function only restricted to the customer User Role? Any way we could allow of enabling for other User Roles? For example, on my site someone becomes a subscriber (default user role for customer with a subscription) when they sign up for a recurring subscription product (like web hosting), so I cannot filter my subscribers or activate/deactivate their Websites/Databases with these tools.

Collin Machine

**Comment by ole1986** [comment]
@MachineITSvcs its hardcoded to customer, but we can change it.
I will create an issue for it to not mixing up PR with other takss

**Comment by MachineITSvcs** [comment]
Perfect!

Collin Machine

**Pull request merged**
